---
before:
  hooks:
    - ./script/download.sh

builds:
  - id: git
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: git
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/repo-scm/git/cmd.BuildTime={{.Date}} -X github.com/repo-scm/git/cmd.CommitID={{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
