---
builds:
  - id: clone
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: clone.go
    binary: clone
    flags:
      - -trimpath
    ldflags: -s -w -X main.BuildTime={{.Date}} -X main.CommitID={{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
